[package]
name = "_pgpq"
version = "0.9.0"
edition = "2021"
readme = "README.md"
license = "MIT"

[lib]
name = "_pgpq"
crate-type = ["cdylib"]

[dependencies]
arrow = {version = "54.1.0", features = ["pyarrow"] }
arrow-schema = "54.1.0"
ahash = "^0.8.11"
bytes = "^1.4.0"
pgpq = { path = "../core" }

[dependencies.pyo3]
version = "^0.23.4"
features = ["extension-module", "abi3-py37"]

[package.metadata.maturin]
name = "pgpq._pgpq"
